/**
 * AUTO-GENERATED — do not edit
 * Generated by mapping initial schema to standard Supabase Database types.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      admin_audit_log: {
        Row: {
          action: string
          actor_id: string
          created_at: string
          id: string
          new_status: string | null
          previous_status: string | null
          target_id: string
        }
        Insert: {
          action: string
          actor_id: string
          created_at?: string
          id?: string
          new_status?: string | null
          previous_status?: string | null
          target_id: string
        }
        Update: {
          action?: string
          actor_id?: string
          created_at?: string
          id?: string
          new_status?: string | null
          previous_status?: string | null
          target_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "admin_audit_log_actor_id_fkey"
            columns: ["actor_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_audit_log_target_id_fkey"
            columns: ["target_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      clients: {
        Row: {
          created_at: string
          id: string
          name: string
          notes: string | null
          phone: string | null
          tailor_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          notes?: string | null
          phone?: string | null
          tailor_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          notes?: string | null
          phone?: string | null
          tailor_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "clients_tailor_id_fkey"
            columns: ["tailor_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      keep_alive: {
        Row: {
          id: string
          pinged_at: string
        }
        Insert: {
          id?: string
          pinged_at?: string
        }
        Update: {
          id?: string
          pinged_at?: string
        }
        Relationships: []
      }
      measurements: {
        Row: {
          client_id: string
          created_at: string
          fields_snapshot: Json
          id: string
          tailor_id: string
          taken_at: string
          template_id: string | null
          template_name_snapshot: string
        }
        Insert: {
          client_id: string
          created_at?: string
          fields_snapshot: Json
          id?: string
          tailor_id: string
          taken_at?: string
          template_id?: string | null
          template_name_snapshot: string
        }
        Update: {
          client_id?: string
          created_at?: string
          fields_snapshot?: Json
          id?: string
          tailor_id?: string
          taken_at?: string
          template_id?: string | null
          template_name_snapshot?: string
        }
        Relationships: [
          {
            foreignKeyName: "measurements_client_id_fkey"
            columns: ["client_id"]
            referencedRelation: "clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "measurements_tailor_id_fkey"
            columns: ["tailor_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "measurements_template_id_fkey"
            columns: ["template_id"]
            referencedRelation: "templates"
            referencedColumns: ["id"]
          }
        ]
      }
      template_fields: {
        Row: {
          field_name: string
          id: string
          order_index: number
          template_id: string
          unit: string | null
        }
        Insert: {
          field_name: string
          id?: string
          order_index?: number
          template_id: string
          unit?: string | null
        }
        Update: {
          field_name?: string
          id?: string
          order_index?: number
          template_id?: string
          unit?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "template_fields_template_id_fkey"
            columns: ["template_id"]
            referencedRelation: "templates"
            referencedColumns: ["id"]
          }
        ]
      }
      templates: {
        Row: {
          created_at: string
          deleted_at: string | null
          id: string
          name: string
          tailor_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          id?: string
          name: string
          tailor_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          id?: string
          name?: string
          tailor_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "templates_tailor_id_fkey"
            columns: ["tailor_id"]
            referencedRelation: "users"
            referencedColumns: ["id"]
          }
        ]
      }
      users: {
        Row: {
          created_at: string
          id: string
          name: string
          plan: string
          role: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id: string
          name: string
          plan?: string
          role?: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          plan?: string
          role?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      admin_tailor_stats: {
        Args: Record<PropertyKey, never>
        Returns: {
          tailor_id: string
          name: string
          status: string
          plan: string
          client_count: number
          template_count: number
          measurement_count: number
          last_activity: string
        }[]
      }
      is_admin: {
        Args: Record<PropertyKey, never>
        Returns: boolean
      }
      tailor_dashboard_stats: {
        Args: Record<PropertyKey, never>
        Returns: {
          client_count: number
          template_count: number
          measurement_count: number
          last_activity: string | null
        }[]
      }
      ping_keep_alive: {
        Args: Record<PropertyKey, never>
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
